# build this using docker
name: Build

on:
  push:
    branches:
      - main

env:
  # --- GCP Configuration ---
    GCP_PROJECT_ID: ${{ vars.GCP_PROJECT_ID }}
    GAR_LOCATION: ${{ vars.GAR_LOCATION }}
    GAR_REPOSITORY: ${{ vars.GAR_REPOSITORY }}
    IMAGE_NAME: ${{ vars.IMAGE_NAME }}
    POOL_ID: ${{ vars.POOL_ID }}
    PROVIDER_ID: ${{ vars.PROVIDER_ID }}

    # --- Cloud Run Configuration ---
    CLOUD_RUN_SERVICE_NAME: ${{ vars.CLOUD_RUN_SERVICE_NAME }}
    CLOUD_RUN_REGION: ${{ vars.CLOUD_RUN_REGION }}

jobs:
  build_push_deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write' # Required for WIF

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - id: auth
      uses: google-github-actions/auth@v2
      with:
        project_id: ${{ env.GCP_PROJECT_ID }}
        workload_identity_provider: 'projects/409124407996/locations/global/workloadIdentityPools/${{env.POOL_ID}}/providers/${{env.PROVIDER_ID}}'
        #service_account: 'github-actions-pusher@${{ env.GCP_PROJECT_ID }}.iam.gserviceaccount.com'

    # --- Setup Docker Buildx ---
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build and Push to GAR
      id: build-push-gar
      uses: docker/build-push-action@v6
      with:
        context: .
        push: true
        tags: |
          ${{ env.GAR_LOCATION }}-docker.pkg.dev/${{ env.GCP_PROJECT_ID }}/${{ env.GAR_REPOSITORY }}/${{ env.IMAGE_NAME }}:latest
          ${{ env.GAR_LOCATION }}-docker.pkg.dev/${{ env.GCP_PROJECT_ID }}/${{ env.GAR_REPOSITORY }}/${{ env.IMAGE_NAME }}:${{ github.sha }}

    # --- Trigger Cloud Run Redeployment ---
    - name: Deploy to Cloud Run
      if: success() # Only run on successful push
      run: |
        gcloud run deploy ${{ env.CLOUD_RUN_SERVICE_NAME }} \
          --image ${{ env.GAR_LOCATION }}-docker.pkg.dev/${{ env.GCP_PROJECT_ID }}/${{ env.GAR_REPOSITORY }}/${{ env.IMAGE_NAME }}:latest \
          --region ${{ env.CLOUD_RUN_REGION }} \
          --project ${{ env.GCP_PROJECT_ID }} \
          --quiet
